export const ADD_TODO = 'add_todo'
export const ASYNC_ADD_TODO = 'async_add'
export const UPDATE_TODO = 'update_todo'
export const COMPLETE_TODO = 'compolete_todo'
export const UNDO_TODO = 'undo_todo'
export const REMOVE_TODO = 'remove_todo'
export const FILTER_TODOS = 'filter_todos'
